name: Build
on: [push]
jobs:
  buildall:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: mkdir build
      - name: CMake
        working-directory: build
        run: pwd && ls .. && cmake ..
      - name: Build
        working-directory: build
        run: make -j `nproc`
    
