name: Simple Action Example
on:
  workflow_dispatch: {}        
  push:
      branches:
        - master

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - run: mkdir build
        working-directory: simple_action/
      - name: CMake
        working-directory: simple_action/build
        run: cmake ..
      - name: Build
        working-directory: simple_action/build
        run: make -j `nproc`
      - name: Test
        working-directory: simple_action/build
        run: ./demo
      - name: Save Exe
        uses: actions/upload-artifact@v4
        with:
          name: demo
          path: simple_action/build/demo
          retention-days: 7

